# Generated by Django 5.2.9 on 2026-01-01 11:25

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('kind', models.CharField(choices=[('UPDATE', 'Update'), ('ALERT', 'Alert')], max_length=16)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('slot_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('xauusd', models.FloatField()),
                ('usdidr', models.FloatField()),
                ('spot_idr_gr', models.FloatField()),
                ('antam_1g_base', models.BigIntegerField()),
                ('antam_1g_pph', models.BigIntegerField()),
                ('buyback', models.BigIntegerField()),
                ('buyback_ts', models.CharField(blank=True, max_length=128)),
                ('spot_source', models.CharField(max_length=64)),
                ('local_source', models.CharField(default='Logam Mulia', max_length=64)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
    ]
